name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo "abdoulaye hi"
    - run: docker build -t udagram-api-feed ./udagram-api-feed
    - run: docker tag udagram-api-feed abdoulayethespy/udagram-api-feed:latest
    - run: docker push abdoulayethespy/udagram-api-feed:latest

    - run: docker build -t udagram-api-user ./udagram-api-user
    - run: docker tag udagram-api-user abdoulayethespy/udagram-api-user:latest
    - run: docker push abdoulayethespy/udagram-api-user:latest

    - run: docker build -t udagram-frontend ./udagram-frontend
    - run: docker tag udagram-frontend abdoulayethespy/udagram-frontend:latest
    - run: docker push abdoulayethespy/udagram-frontend:latest

    - run: docker build -t reverseproxy ./udagram-reverseproxy
    - run: docker tag reverseproxy abdoulayethespy/reverseproxy:latest
    - run: docker push abdoulayethespy/reverseproxy:latest
